Training react
wolox-training/ao-react-native pull request #10
Opened 2018-09-28 21:47 UTC by andyOlarte514

# Summary
- add folder `finger-exercises` and run test of `01 - spread`, `02 - promises` in folder `ecmascript`

# Trello Card
- https://trello.com/c/FwOpueoK

2018-10-01 14:46 UTC, henryzarza requested changes
Good work! Only a few comments

2018-10-01 14:46 UTC, henryzarza commented on training-react/finger-exercises/ecmascript/01 - spread/index.js
> +  if (param !== undefined && param !== null) {
You can replace this condition for `if (param)` see this [post](https://www.sitepoint.com/javascript-truthy-falsy/)

2018-10-01 14:46 UTC, henryzarza commented on training-react/finger-exercises/ecmascript/01 - spread/index.js
> +    } else if (arg.length > 0) {
Same here, you can replace for `arg.length`

2018-10-01 14:46 UTC, henryzarza commented on training-react/finger-exercises/ecmascript/01 - spread/index.js
> +export function copy(data) {
You can replace this for `return isArray(data) ? [...data] : { ...data }`

2018-10-01 14:46 UTC, henryzarza commented on training-react/finger-exercises/ecmascript/01 - spread/index.js
> +export function reverseMerge(arr1, arr2) {
You can replace the `push` function for `concat` function, see this [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)

2018-10-02 14:56 UTC, henryzarza submitted a review, later dismissed
Good work 👍

2018-10-02 15:05 UTC, wfolini requested changes
Great! Min change and go!

2018-10-02 15:05 UTC, WFolini commented on training-react/finger-exercises/ecmascript/01 - spread/index.js
> +  return newArr;
U can return `[...arr2, ...arr1]`

2018-10-02 16:18 UTC, wfolini approved these changes

2018-10-02 16:18 UTC, merged