Training react tic tac toe
wolox-training/ao-react-native pull request #11
Opened 2018-10-02 20:02 UTC by andyOlarte514

# Summary
- Create app tic tac toe with `create-react-app --scripts-version wolox-react-scripts`
- Development of the react tutorial
- wolox folder structure
- Css Modules

# Trello Card
- https://trello.com/c/6N5S5Wyy

# Screenshots
![tic tac toe](https://user-images.githubusercontent.com/40371687/46373386-87ef6b00-c653-11e8-80e3-10959e92151f.gif)

2018-10-03 03:16 UTC, wfolini requested changes
Excellent!
Let's start to apply a little the react conventions that we handle in Wolox. I made you some comments so that we can refactor the app according to these conventions.

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/components/Square/styles.scss
> +}
Missing EOF here

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/index.js
> +  onClick: PropTypes.func
Both `isRequired`

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/styles.scss
> +}
Missing EOF here

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/styles.scss
> +}
Missing EOF here

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/package.json
> +}
Missing EOF here

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/index.js
> +  renderSquare = i => <Square value={this.props.squares[i]} onClick={() => this.props.onClick(i)} />;
Avoid the use of arrow functions in a render. Check here why is a problem https://medium.freecodecamp.org/why-arrow-functions-and-bind-in-reacts-render-are-problematic-f1c08b060e36
To solve that, u must extract this component in another file

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/index.js
> +    const lines = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];
This const never change. A good approach is extract this type of const in another file, like `src/constants/game.js`

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/index.js
> +    const moves = history.map((step, move) => {
I'd extract `moves` as a another component in another file

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/index.js
> +          <button onClick={() => this.jumpTo(move)}>{desc}</button>
So, we can extract this onClick function as a instance of these component and avoid the arrow function in the render

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/index.js
> +    let status;
I'd extract this status calculation as a function of this class component

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/index.js
> +class App extends Component {
Since this component is a stateless component, I'd refactor it to a functional component, following this https://github.com/Wolox/tech-guides/blob/master/react/style-guide.md#class-vs-reactcreateclass-vs-stateless

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/styles.scss
> +}
This is a global style. Move it to `scss/application.scss`

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/styles.scss
> +}
Same this

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/index.js
> +import App from '~components/App'; // eslint-disable-line import/first
U can avoid this eslint issues replacing `~` character to `@`for all aliases in `.babelrc` file

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/scss/index.scss
> +body {
I'd rename this file to `application.scss`

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/components/Square/index.js
> +function Square(props) {
Do props destructuring in the function params following this https://github.com/Wolox/tech-guides/blob/master/react/style-guide.md#props

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/components/Square/styles.scss
> +  border: 1px solid #999;
All colors must be extracted in `scss/variables/_colors.scss`, so un can change theme colors just in one file, avoiding changing them in each component style file

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/styles.scss
> +}
All these style classes are unuses. Delete them

2018-10-03 03:16 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/components/Square/index.js
> +  onClick: PropTypes.func
Both propTypes are required

2018-10-03 14:14 UTC, henryzarza requested changes

2018-10-03 14:14 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/components/Square/styles.scss
> +.square:focus {
Put this pseudo class inside of the class `.square`. Remember the nesting in SASS, you could read [this](https://github.com/Wolox/tech-guides/blob/master/frontend/docs/style-guide.md#using-parent)

2018-10-03 14:14 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/styles.scss
> +.board-row:after {
You can delete this, is a clearfix and isn't necessary also it's a bad practice in CSS

2018-10-03 14:14 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/index.js
> +    if (winner) {
You could change for this: ``status = winner ? `Winner: ${winner}` : `Next player: ${this.state.xIsNext ? 'X' : 'O'}`
``

2018-10-03 14:14 UTC, henryzarza commented on training-react/tic-tac-toe/src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3">
Delete this file, isn't necessary

2018-10-03 14:14 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/index.scss
> +  font-family: sans-serif;
Remember order by alphabetically

2018-10-03 22:52 UTC, henryzarza requested changes
Good work! Only a few corrections

2018-10-03 22:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/board.js
> +  squares: node.isRequired,
Change this PropType for `arrayOf`

2018-10-03 22:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Moves/components/Step/step.js
> +      <li key={move}>
The `key` should be put where you do the `map` in this case in the `renderMoves` function in the `Moves` component. Also remember that the `key` shouldn't be the array index.

2018-10-03 22:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Moves/moves.js
> +  history: arrayOf(shape),
I think that `shape` PropTypes should have the types

2018-10-03 22:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/game.js
> +          <Board squares={current.squares} onClick={i => this.handleClick(i)} />
Remember not call functions in the render

2018-10-04 14:55 UTC, henryzarza submitted a review, later dismissed
Good job. Check my comment before merging

2018-10-04 14:55 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Moves/moves.js
> +    return <Step key={move} onClick={jump} move={move} />;
Remember not assign the array index as key

2018-10-04 16:22 UTC, henryzarza submitted a review, later dismissed
Great 🥇

2018-10-04 18:23 UTC, wfolini requested changes
Last comments and go!

2018-10-04 18:23 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/board.js
> +import React, { Component, Fragment } from 'react';
Name this file `index.js`, so u can import it just like `import Board from './components/Board';`

2018-10-04 18:23 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/components/Square/square.js
> +import React, { PureComponent } from 'react';
Name this file `index.js`

2018-10-04 18:23 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Moves/components/Step/step.js
> +import React, { PureComponent } from 'react';
Name this file `index.js`

2018-10-04 18:23 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Moves/moves.js
> +import React, { Component } from 'react';
Name this file `index.js`

2018-10-04 18:23 UTC, wfolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/game.js
> +import * as gameConsts from '@consts/game';
Name this file `index.js`

2018-10-04 19:10 UTC, wfolini approved these changes
👏 👏

2018-10-04 19:11 UTC, merged