React redux
wolox-training/ao-react-native pull request #12
Opened 2018-10-08 22:45 UTC by andyOlarte514

# Summary
- install `redux`
- install `react-redux`
- install `redux-thunk`
- add the folder `redux`
- add the file `store.js`
- add the the folder `game` into folder `redux`
- add the files `actions.js` and `reducer.js` into `game` folder
- apply `react-redux` in `index.js` file
- apply `redux-thun` in `store.js` file
- modify component `Game`

# Trello Card
- https://trello.com/c/Ww6VPmKr

2018-10-09 15:51 UTC, henryzarza requested changes
Good job 👍 . Remember upload the screenshot

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/constants/game.js
> +export const actionsTypes = {
Action types shouldn't be here, put it in the `redux/game/actions` file

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/index.js
> +  history: arrayOf(
This props `isRequired`

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/constants/game.js
> +export const calculateWinner = squares => {
This function should be in a file called `utils` because isn't a const.

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +import { actionsTypes, calculateWinner } from '@consts/game';
The actions types constant should be here

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +const jumpToStep = step => ({
Move all the functions that you export to a variable called `actionCreators` and export it

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +const clickSquare = i => (dispatch, getState) => {
Same here

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +  const step = `step${getState().game.stepNumber + 1}`;
Create a variable and assign it this value, because you use this twice

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +  squares[i] = getState().game.xIsNext ? 'X' : 'O';
Same situation here

2018-10-09 15:51 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +export { jumpToStep, clickSquare };
Export the `actionCreators` as default

2018-10-09 20:02 UTC, henryzarza submitted a review, later dismissed
Good 👍 , you look my comments before the merge

2018-10-09 20:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/App/components/Game/components/Board/components/Square/styles.scss
> +  cursor: pointer;
Remember order by alphabetically

2018-10-09 20:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +    const currentState = getState().game.stepNumber;
Assign a name more descriptive, for example: `stepNumber` and you could do `destructuring assignment`

2018-10-10 14:47 UTC, wfolini requested changes
Great! Two little changes

2018-10-10 14:47 UTC, WFolini commented on training-react/tic-tac-toe/src/app/components/App/components/Game/index.js
> +)(Game);
Let's split this component in a smart and presentational component. All redux connection should be placed in container component, and int the presentational one u must only handle the layout.
Check [this](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) and [this](https://medium.com/@learnreact/container-components-c0e67432e005)

2018-10-10 14:47 UTC, WFolini commented on training-react/tic-tac-toe/src/utils/utils.js
> +const linesConsts = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];
Move `linesConsts` to `src/constants/game.js`

2018-10-10 18:29 UTC, wfolini requested changes

2018-10-10 18:29 UTC, WFolini commented on webpack-4-quickstart/.babelrc
> +{
This folder is outside the scope of this pr. Delete it

2018-10-10 18:38 UTC, wfolini approved these changes
👌 👌

2018-10-10 18:38 UTC, merged