Form login
wolox-training/ao-react-native pull request #15
Opened 2018-10-16 15:27 UTC by andyOlarte514

# Summary
- Initial Setup from Login
- Creation of login in the `tic-tac-toe` project

# Trello Card
- https://trello.com/c/JzNvOE3Z

2018-10-16 20:52 UTC, henryzarza requested changes
Good check my comments 😄

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/index.js
> +export const customInput = props => {
Change this. Export the component at the end, for example: `function customInput({ input, type, meta, placeholder }) { ... }` and export it `export default customInput;`

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/index.js
> +  const { input, type, meta, placeholder } = props;
You should be the destructuring in the definition of the function and not here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/index.js
> +      <input {...input} type={type} className={style.customInput} placeholder={placeholder} />
If you only use here a component `input` I think that you should change the name of this component

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +  height: 78px;
Remember order by alphabetically

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +  margin: 0 0 15px 0;
You can use `margin-bottom` property and not the shorthand

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +    font-family: "Roboto", sans-serif;
It's a bad practice assign `font-family` property here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +    background: #f2f2f2;
Move this color to `_colors.scss` file

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/index.js
> +    <div className={cx(style.customInputContainer, { dirty: meta.dirty }, getValidityClassName(meta))}>
I think that isn't necessary use a library for this, you could be this with `sass modules` only

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/index.js
> +import cx from 'classnames';
Delete this

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/package.json
> +    "classnames": "^2.2.6",
This library isn't necessary

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +    border: 0;
Remember the order

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +    box-sizing: border-box;
It's a bad practice assign `box-sizing:` property here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +      width: 0;
Order by alphabetically

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +      height: 0;
The same

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Fields/styles.scss
> +    border-color: $gray_mercury;
The same

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/index.js
> +const LoginContainer = () => <Layout />;
Remember not assign the functional components as arrow functions. Check this [style guide](https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless)

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/layout.js
> +    const log = () => console.log('hola');
Change the name

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/layout.js
> +              src="https://www.wolox.com.ar/assets/img-logo-wolox-color-93cbcc9f2c.svg"
It would be better if you import the url of the image at the beginning of the file. Also download this image and move it to the `assets` folder.

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/layout.js
> +const Form = reduxForm({
I think that isn't necessary this. Change for: `export default reduxForm({form: 'login'})(Layout);`

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +  composes: d-flex j-center a-center;
Is really necessary this?

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +@import url(https://fonts.googleapis.com/css?family=Roboto:300);
Not import the typography here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +  height: 100vh;
Remember the order

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +  background: #FFFFFF;
Move this color to `_colors.scss` file

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +  z-index: 1;
The same here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
The same with this colors

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +  button {
Isn't a good practice to apply styles to general HTML elements. You could use classes

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    font-family: "Roboto", sans-serif;
Remember the import of the fonts here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    background: $blue_indigo;
Remember the order

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    color: #FFFFFF;
Move this color a `_colors.scss` file

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    -webkit-transition: all 0.3 ease;
This isn't necessary

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    cursor: pointer;
The order

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    border-color: gray;
Move this color a _colors.scss file

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    border-color: #eee;
The same here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    border-color: gray;
The same here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/login/actions.js
> +export const actiosTypes = {};
Change the name

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/store.js
> +  form: formReducer
And the others reducers?

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/application.scss
> +  -webkit-font-smoothing: antialiased;
Isn't necessary

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/application.scss
> +  -moz-osx-font-smoothing: grayscale;
The same here

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/reusable/_flexbox.scss
> +.d-flex {
I think that this file isn't necessary

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/settings/_fonts.scss
> +}
Add EOF

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/variables/_colors.scss
> +$blue_indigo: #4158d0;
Remember order by alphabetically

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/validations/index.js
> +  !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(value) ? 'Email invalido' : undefined;
Change the text for `Email inválido`

2018-10-16 20:52 UTC, henryzarza commented on training-react/tic-tac-toe/src/validations/index.js
> +  value.length < 8 ? 'Este campo debe tener como minimo 8 caracteres' : undefined;
Change the text for `Este campo debe tener como mínimo 8 caracteres`

2018-10-17 17:02 UTC, henryzarza requested changes

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Input/index.js
> +  if (meta.active) {
This condition you could omit

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Input/index.js
> +function customInput({ input, type, meta, placeholder }) {
In where is the `propTypes`?

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Input/styles.scss
> +    background: $concrete;
Change this for `background-color` property

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Input/styles.scss
> +    animation-name: grey-pulse;
In where is defined the animation?

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/index.js
> +function login({ handleSubmit }) {
The name of the components should be in `PascalCase`, check this [style guide](https://github.com/airbnb/javascript/tree/master/react#naming)

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/index.js
> +  mapStateToProps,
You aren't using this at the time assign it in null

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/layout.js
> +import { required, minLength, email } from '@validations';
This import should be below the import of `prop-types`

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +  position: relative;
I think that this property isn't necessary

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    border: 0;
I think that this property isn't necessary. Check the `equalizer` file

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    cursor: pointer;
The same here

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +    outline: 0;
And here

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +  text-align: center;
The same here

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +@keyframes grey-pulse {
You don't use this so delete it

2018-10-17 17:02 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/settings/_fonts.scss
> +@font-face {
You never use this so delete it

2018-10-17 20:34 UTC, henryzarza submitted a review, later dismissed
Good job. Check my comments before that you do merge

2018-10-17 20:34 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/Input/index.js
> +        meta.touched && meta.valid ? style.valid : ''
Order this

2018-10-17 20:34 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/login/actions.js
> +  HAS_ERR_USER: 'HAS_ERR_USER'
Change this name for `HAS_ERROR_USER`

2018-10-18 16:05 UTC, wfolini requested changes
Excellent PR! Only two comments and go!

2018-10-18 16:05 UTC, WFolini commented on training-react/tic-tac-toe/src/app/screens/Login/layout.js
> +
Delete this space

2018-10-18 16:05 UTC, WFolini commented on training-react/tic-tac-toe/src/redux/login/actions.js
> +    if (!response.data.error) {
use `response.ok`

2018-10-19 20:34 UTC, wfolini approved these changes

2018-10-19 20:36 UTC, merged