Top bar
wolox-training/ao-react-native pull request #17
Opened 2018-10-23 19:11 UTC by andyOlarte514

#Summary
- Add TopBar
- Add Profile (Initial Setup)
- Modify Styles

# Trello Card
- https://trello.com/c/VBIXij52

2018-10-23 23:03 UTC, henryzarza requested changes
You always forget the screenshots 😞

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/package.json
> +    "i": "^0.3.6",
Delete this isn't necessary

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/package.json
> +    "npm": "^6.4.1",
The same here

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/index.js
> +    <header className={styles.header}>
Change this tag for `nav`

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/index.js
> +        <nav className={styles.navBar}>
Change this tag for a `div` and the same recommendation above

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/index.js
> +        <div className={styles.logo}>
Is it necessary this? I think that you could simplify the structure

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/styles.scss
> +    width: 90%;
Why you do this? I think you can replace this for `padding` property

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/styles.scss
> +    .nav-bar {
Add a break line

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/styles.scss
> +      flex-wrap: wrap;
This is repeated delete it

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/styles.scss
> +        min-width: 80px;
You should assign only a of the 2 properties `max-width` or `min-width`

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/styles.scss
> +  .options-header {
Add a break line

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/screens/Profile/index.js
> +}
Add a break line

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/styles.scss
> +      background: $apple;
Change this for `background-color` property

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/application.scss
> +html,
Delete this selector

2018-10-23 23:03 UTC, henryzarza commented on training-react/tic-tac-toe/src/scss/application.scss
> +#root {
Isn't a good approach to assign styles with id selectors

2018-10-24 15:30 UTC, wfolini requested changes
I need a GIF capture interaction between the screens routing for approve this PR. Please, upload it.

2018-10-24 15:30 UTC, wfolini commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/index.js
> +)(Header);
Split this component into a smart and dumb component

2018-10-24 15:30 UTC, wfolini commented on training-react/tic-tac-toe/src/app/screens/Home/components/Header/index.js
> +import { func } from 'prop-types';
Don't apply destructuring in propTypes. Goes against to snippets

2018-10-24 19:06 UTC, henryzarza approved these changes

2018-10-24 19:07 UTC, wfolini approved these changes

2018-10-24 19:07 UTC, merged