Redux recompose
wolox-training/ao-react-native pull request #20
Opened 2018-10-30 14:06 UTC by andyOlarte514

# Summary
- Integration with `redux-recompose`

# Trello card
- https://trello.com/c/DbWtknPz

2018-10-30 18:54 UTC, henryzarza requested changes
Good job, only a few comments.

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/screens/Profile/components/Form/index.js
> +      ) : hasError ? (
You could replace this for: `hasError && <span className={styles.failureUpdate}>Error in update user data</span>`

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/package.json
> +    "ajv": "^6.5.4",
Do you need this?

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/index.js
> +  hasError: PropTypes.string
Change this prop type for `bool`

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/index.js
>  const mapStateToProps = state => ({
You could do destructuring

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/layout.js
> +  hasError: PropTypes.string
Change the name for something more descriptive

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +    target: 'game',
Assign `game` target value to `const`

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/actions.js
> +      target: 'game',
The same here

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/game/reducer.js
> +const reducerEffects = {
Good approach 👏

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/login/actions.js
> +    target: target.AUTH,
Change this for `IS_AUTH `

2018-10-30 18:54 UTC, henryzarza commented on training-react/tic-tac-toe/src/redux/login/actions.js
> +    target: target.AUTH,
The same here

2018-10-30 19:18 UTC, henryzarza submitted a review, later dismissed

2018-10-30 22:00 UTC, wfolini requested changes
Excellent! Good work! Some comments and go!

2018-10-30 22:00 UTC, wfolini commented on training-react/tic-tac-toe/package.json
> +    "ajv": "^6.5.4",
U aren't using this. Delete it

2018-10-30 22:00 UTC, wfolini commented on training-react/tic-tac-toe/src/redux/profile/reducer.js
> +  updateUser: null,
U don't need to save `getUser` and `updateUser`, Delete it

2018-10-30 22:00 UTC, wfolini commented on training-react/tic-tac-toe/src/redux/profile/actions.js
> +    target: target.UPDATE_USER,
U can delete this target

2018-10-30 22:00 UTC, wfolini commented on training-react/tic-tac-toe/src/redux/profile/actions.js
> +    target: target.GET_USER,
Also this

2018-10-30 22:00 UTC, wfolini commented on training-react/tic-tac-toe/src/services/profileService.js
> +    const idUSer = localStorage.getItem('userId');
U don't need to save this user id in the local storage. Save it in the redux store, and then, u can read it from a thunk action with `getState`. Check this https://github.com/reduxjs/redux-thunk#motivation

2018-10-30 22:00 UTC, wfolini commented on training-react/tic-tac-toe/src/services/profileService.js
> +    const idUSer = localStorage.getItem('userId');
Same here

2018-10-30 22:43 UTC, andyOlarte514 commented on training-react/tic-tac-toe/src/redux/profile/actions.js
> +    target: target.UPDATE_USER,
if I remove the target, this happens:

![image](https://user-images.githubusercontent.com/40371687/47755143-3a264c80-dc6b-11e8-8599-293c04da0c41.png)

2018-10-30 22:43 UTC, andyOlarte514 commented on training-react/tic-tac-toe/src/redux/profile/actions.js
> +    target: target.GET_USER,
same

2018-10-31 14:58 UTC, wfolini approved these changes
Excellent!

2018-10-31 14:58 UTC, WFolini commented on training-react/tic-tac-toe/src/redux/login/actions.js
> +        const idUser = response.data.userId;
`const { token, userId }  = response.data;`

2018-10-31 15:12 UTC, merged