Higher order component
wolox-training/ao-react-native pull request #21
Opened 2018-10-31 15:15 UTC by andyOlarte514

# Summary 
- Implementation of `higher order component`

# Trello Card
- https://trello.com/c/JkXViBb1

2018-10-31 18:23 UTC, henryzarza requested changes

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/HOC/index.js
> +function HigherOrderComponent(WrappedComponent) {
Change the name the folder `HOC` for something more descriptive and also change the name of this component `HigherOrderComponent`

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/HOC/index.js
> +  class HOC extends Component {
The same here and i think that you could change this to function component

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/HOC/index.js
> +      const { loading, ...props } = this.props;
Remember the prop types

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/HOC/styles.scss
> +    border-color: $white transparent $white transparent;
The colors should be in `_colors.scss` file

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/HOC/styles.scss
> +    content: ' ';
Delete the space

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/HOC/styles.scss
> +  display: inline-block;
I think that you don't need this

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/components/RouteCheck/index.js
> +    const loading = this.props.loading;
Use destructuring here

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Home/screens/Profile/index.js
> +        loading={loading}
You don't use this prop in the `Layout` component so delete it

2018-10-31 18:23 UTC, henryzarza commented on training-react/tic-tac-toe/src/app/screens/Login/index.js
> +import HCO from '@components/HOC';
Change this name

2018-10-31 21:09 UTC, henryzarza approved these changes

2018-11-01 00:44 UTC, wfolini reviewed
Great! Looks good to me. Can u upload a GIF showing the HOC in action?

2018-11-01 14:24 UTC, wfolini approved these changes
:clap:

2018-11-01 14:45 UTC, merged