Maquetado grid
wolox-training/ao-react-native pull request #8
Opened 2018-09-26 18:52 UTC by andyOlarte514

# Summary
- modify the archive `techs.scss` for apply css grid

# Trello Card
- https://trello.com/c/5NBAcwpa

# Screenshots

![image](https://user-images.githubusercontent.com/40371687/46102146-4104ff80-c193-11e8-9dda-d65fad71950e.png)

2018-09-26 19:47 UTC, CarlosHWolox commented on training-maquetado/scss/techs.scss
> +  grid-template-areas: 'frist-tech . .''frist-tech . .';
first?

2018-09-26 19:51 UTC, braiandickson requested changes

2018-09-26 19:51 UTC, braiandickson commented on training-maquetado/scss/techs.scss
>    p {
Check this p element.

2018-09-26 23:06 UTC, braiandickson approved these changes

2018-09-27 13:24 UTC, andyOlarte514 commented on training-maquetado/scss/techs.scss
> +  grid-template-areas: 'frist-tech . .''frist-tech . .';
solved

2018-09-27 16:02 UTC, CarlosHWolox approved these changes

2018-09-27 16:04 UTC, merged